name: Deploy to GitHub Pages

# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]
  
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v2.7.0
    # sets up .NET Core SDK 3.1
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 7.0
    # install node_modules
    - name: install node modules
      uses: tecolicom/actions-install-node-modules@v1.2
    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish julyoc.github.io.csproj -p GHPages=true -o public -c Release
    # Deploy the site
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: public/wwwroot
        force_orphan: true
